const totalJobs = [
    {
        id: 1,
        title: "Senior Product Manager",
        rating: 4,
        review: 336,
        location: "California, CA",
        jobOption: ["Full time", "Senior level", "Remote"],
        salary: "$2.5k",
        bgColor: "#F8FAFC",
    },
    {
        id: 2,
        title: "Software Engineer",
        rating: 5,
        review: 420,
        location: "New York, NY",
        jobOption: ["Full time", "Mid-level", "On site"],
        salary: "$3k",
        bgColor: "#E0F2FE",
    },
    {
        id: 3,
        title: "Machine Learning Engineer",
        rating: 4,
        review: 298,
        location: "Seattle, WA",
        jobOption: ["Full time", "Remote", "Senior level"],
        salary: "$3.5k",
        bgColor: "#FEF3C7",
    },
    {
        id: 4,
        title: "Data Scientist",
        rating: 4,
        review: 370,
        location: "Austin, TX",
        jobOption: ["Part time", "Remote", "Mid-level"],
        salary: "$2.8k",
        bgColor: "#D1FAE5",
    },
    {
        id: 5,
        title: "Frontend Developer",
        rating: 3,
        review: 250,
        location: "San Francisco, CA",
        jobOption: ["Full time", "On site", "Junior level"],
        salary: "$2.7k",
        bgColor: "#FCE7F3",
    },
    {
        id: 6,
        title: "Backend Developer",
        rating: 4,
        review: 315,
        location: "Boston, MA",
        jobOption: ["Full time", "Mid-level", "Remote"],
        salary: "$3.2k",
        bgColor: "#FDE68A",
    },
    {
        id: 7,
        title: "DevOps Engineer",
        rating: 5,
        review: 412,
        location: "Denver, CO",
        jobOption: ["Full time", "Senior level", "On site"],
        salary: "$3.8k",
        bgColor: "#DBEAFE",
    },
    {
        id: 8,
        title: "Cybersecurity Analyst",
        rating: 4,
        review: 278,
        location: "Chicago, IL",
        jobOption: ["Part time", "Remote", "Mid-level"],
        salary: "$3.1k",
        bgColor: "#F3E8FF",
    },
    {
        id: 9,
        title: "Embedded Systems Engineer",
        rating: 4,
        review: 290,
        location: "Los Angeles, CA",
        jobOption: ["Full time", "On site", "Senior level"],
        salary: "$3.4k",
        bgColor: "#FFEDD5",
    },
    {
        id: 10,
        title: "Cloud Architect",
        rating: 3,
        review: 500,
        location: "Miami, FL",
        jobOption: ["Full time", "Remote", "Senior level"],
        salary: "$4k",
        bgColor: "#D1D5DB",
    },
];

export {totalJobs}